---
teams:
  Crows Before Hoes:
    - Tom Brady
    - Eli Manning
    - Frank Gore
    - Doug Martin
    - Antonio Brown
    - Odell Beckham
    - Amari Cooper
    - Arian Foster
    - Marvin Jones
    - Matt Jones
    - Carlos Hyde
  Admirals:
    - Russell Wilson
    - Ryan Tannehill
    - Justin Forsett
    - Andre Ellington
    - Calvin Johnson
    - Antonio Brown
    - Travis Kelce
    - Doug Martin
    - C.J. Spiller
    - Shane Vereen
    - Anquan Boldin
    - Marques Colston
    - Zach Ertz

...