---
teams:
  Peanuts:
    - Marcus Mariota
    - Andrew Luck
    - Christian McCaffrey
    - Derrick Henry
    - Alvin Kamara
    - Dion Lewis
    - C.J. Prosise
    - Jalen Richard
    - Amari Cooper
    - Michael Thomas
    - Jarvis Landry
    - Will Fuller
    - Chris Godwin
    - Kenny Golladay
    - DeVante Parker
    - Allen Robinson
    - Eric Ebron
    - Tyler Eifert

...
